### ISSUE TITLE
Internal fuel reverts to 50% everytime mission is openend with new DCS session

### ISSUE THREAD

**Issue by ataribaby42** [heclak/community-a4e-c#236]
Looks like there is a bug - everytime I set internal fuel to 100% for A-4 and save mission and close DCS and open mission again in editor there is back 50% internal fuel.

**Comment by heclak** [comment]
noted about this bug but this might be a hard one to track down. I'll what I can do, I'm worried that it is another sign of SFM support breaking.

**Comment by Andrew8604** [comment]
Agree.  I've been playing around with a single-player mission centered around the A-4E-C and including several AI aircraft.  I noticed this issue (DCS ver. 54046) with my own A-4E as well as all A-4E-C's in AI flights.  It does not seem to occur with F-4E's that I also have in my mission (also SFM, right?).  I have my single A-4, a flight of 3 A-4's (AI - that I join the formation of, but I don't want them attached to me,) and 2 additional flights of 4 A-4's in this mission.  All set to "Start from Ramp".  And I have to set the fuel from 50% to 100% on every one of them...except, oddly, element number 4 of the 3rd flight was already set to 100%, this last time...strange (I've haven't been able to replicate that, though).    Additionally, I have 2 single-ship flights of A-4's that begin the mission in flight (as incidental arrivals to the airport).  I set them to reduced fuel (40%, as they are ending their flight).  Curiously, it seemed like this problem began after setting those 'in flight' units to reduced fuel.  So, to test, I set them to 100%. and saved and re-launched DCS.  And, the problem affects them, too...50%.  Apparently, if they are set to less than 50%, it remembers what they are set to.  I'll have to experiment.  That and with a fresh, new mission, and see what the behavior is.  As well as missions created before 54046.

BTW, v. 54046 seems to check for updates every time I launch DCS.  Seems like other versions only checked once per day.

And, I could try updating to the latest version of DCS and test again.  Man!!  This is time consuming, trying to "corner" a problem.  They release new versions rather too frequently, now.

Will the A-4E-C eventually become unusable with some version of DCS, if/when they make a change that breaks what you all have done to create it?

Can you tell me with any detail and certainty why obtaining a license from Boeing for the A-4 Skyhawk in DCS is so problematic compared with the F/A-18C and other modules?

**Comment by Andrew8604** [comment]
Same 50% fuel problem with the A-4E-C in a mission I last saved back on Aug 22nd, which predates v. 54046.  I sure don't remember the problem back before October.  However, it appears I hadn't flown the A-4 between Aug 22nd and Oct 5th.  It was October 5th, with ver. 54046, (and A-4E-C ver 1.4.0) where I noticed many things not working... flight computer, doppler control panel, TACAN indicator, and several others.  I upgraded to the current A-4E-C version (1.4.2, right?) and that fixed everything (I think), but then I noticed the fuel issue here.  I'm going to upgrade DCS to latest and see what happens.  ...and hopefully those won't be famous last words on the A-4E-C.  :)

**Comment by Andrew8604** [comment]
Upgraded to DCS v55960.  The 50% fuel problem for the A-4E-C's in my mission still remained...well, it did for about 10 of 14 A-4's.  4 of them had 100% fuel.  So, it is somewhat intermittent.  Weird.  All the A-4E-C's had their livery changed to default.  Whereas, I had them all set for VMA-211.   That apparently happened upon upgrading to v55960.

**Comment by callmepartario** [comment]
fuel calculations have been addressed in the EFM, so closing this issue for now.

**Comment by ataribaby42** [comment]
It still happens to me even with EFM 2.0 beta 2

I have feel it happens if you revisit A-4 in editor and touch loadout and then save and reload mission in editor A-4 unit will have 50% internal fuel.

**Comment by 08jne01** [comment]
Yea this is not something we can set from the EFM, the EFM simply fills with the amount it's told to fill.
